image: public.ecr.aws/sam/build-nodejs18.x:latest

stages:
  - deploy
  
variables:
  STACK_NAME: AWS-Github-OIDC-connection
  STACK_REGION: eu-west-2

backend:
  stage: deploy
  script:
    - sam build
    - sam package --output-template-file packaged.yaml --s3-bucket $S3_DEPLOY_BUCKET --region $STACK_REGION
    - sam deploy --no-fail-on-empty-changeset --template-file packaged.yaml --stack-name $STACK_NAME --s3-bucket $S3_DEPLOY_BUCKET --capabilities CAPABILITY_NAMED_IAM --region $STACK_REGION --parameter-overrides GitHubEntity=$GITHUB_ORG
