AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  OIDCProviderUrl:
    Type: String
    Description: URL of the github actions provider
    Default: 'https://token.actions.githubusercontent.com'
  OIDCProviderThumbprint:
    Type: String
    Description: Thumbprint of the github actions provider (AWS No longer validate thumbprints for Github, Gitlab, Auth0 & Google https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc_verify-thumbprint.html (A value must still be provided)). Can also be a comma seperated list of Thumbprints. E.g. a,b,c
    Default: '1b511abead59c6ce207077c0bf0e0043b1382612'
  OIDCProviderClientId:
    Type: String
    Description: ClientId / Audience for the github actions provider. Can also be a comma seperated list of Clients. E.g. a,b,c
    Default: 'sts.amazonaws.com'
  GitHubEntity:
    Type: String
    Description: Name of the your Github Account or Organisation to scope access to.
    Default: ''

Resources:
  oidcProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: !Ref OIDCProviderUrl
      ThumbprintList: !Split [',', !Ref OIDCProviderThumbprint]
      ClientIdList: !Split [',', !Ref OIDCProviderClientId]
  
  oidcRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-Role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                - !GetAtt oidcProvider.Arn
            Action:
              - sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub:
                  - !Sub "repo:${GitHubEntity}/*"
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"

Outputs:
  oidcRoleName:
    Value: !Ref oidcRole
    Description: This is the role that should be assumed in the github action workflow
  oidcRoleArn: 
    Value: !GetAtt oidcRole.Arn
    Description: This is the role ARN that should be assumed in the github action workflow
